---
# tasks file for nginx
- name: libselinux-python과 EPEL Repository 설치
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - libselinux-python
    - epel-release

- name: nginx 설치
  yum:
    name: nginx
    state: present

- name: nginx 시작과 자동 시작 설정
  service:
    name: nginx
    state: started
    enabled: true

- name: nginx.conf 템플릿 활용
  template:
    src: nginx.j2.conf
    dest: /etc/nginx/nginx.conf
    validate: nginx -t -c %s
  notify:
    - nginx reload

- name: nginx용 그룹 작성
  group:
    name: "{{ nginx_group }}"
    system: true

- name: nginx용 사용자 생성
  user:
    name: "{{ nginx_user }}"
    home: /var/lib/nginx
    shell: /sbin/nologin
    groups: "{{ nginx_group }}"
    append: true
    system: true
