---
  - hosts: localhost
    connection: local
    gather_facts: false
    tasks:
      - name: Retrieve facts
        stat:
          path: ./sshd-pid-exist-test.pid
        register: p

      - name: Debug and print stat variables
        debug:
          msg: "{{ p }}"

      - name: Determine if path exists and file size is more than 1 byte
        assert:
          that:
            - p.stat.exists
            - p.stat.size > 1
