---
  - hosts: master
    become: true
    gather_facts: false
    tasks:
      - name: Restarted sshd
        systemd:
          name: sshd
          state: restarted

      - name: Wait for ssh is available
        wait_for:
          port: 22
          search_regex: OpenSSh
          delay: 5
